// Generated by scripts/sync-docs.mjs. Do not edit by hand.

export const frameworkAdrDocs = [
  {
    slug: 'adr-0001-channel-session-sender-scope',
    title: {
      zh: 'ADR 0001: Sender-Scoped Channel Sessions',
      en: 'ADR 0001: Sender-Scoped Channel Sessions',
    },
    filePath: './content/echo-agent/adr/0001-channel-session-sender-scope.md',
  },
  {
    slug: 'adr-0002-sandbox-cancellation-cleanup',
    title: {
      zh: 'ADR 0002: Sandbox Cancellation Cleanup',
      en: 'ADR 0002: Sandbox Cancellation Cleanup',
    },
    filePath: './content/echo-agent/adr/0002-sandbox-cancellation-cleanup.md',
  },
  {
    slug: 'adr-0003-tracked-steer-lifecycle',
    title: {
      zh: 'ADR 0003: Tracked Steering Lifecycle',
      en: 'ADR 0003: Tracked Steering Lifecycle',
    },
    filePath: './content/echo-agent/adr/0003-tracked-steer-lifecycle.md',
  },
  {
    slug: 'adr-0004-async-file-store-ownership',
    title: {
      zh: 'ADR 0004: Async File Store Ownership',
      en: 'ADR 0004: Async File Store Ownership',
    },
    filePath: './content/echo-agent/adr/0004-async-file-store-ownership.md',
  },
  {
    slug: 'adr-0005-invocation-resource-lifetime',
    title: {
      zh: 'ADR 0005: Invocation Resource Lifetime Guards',
      en: 'ADR 0005: Invocation Resource Lifetime Guards',
    },
    filePath: './content/echo-agent/adr/0005-invocation-resource-lifetime.md',
  },
  {
    slug: 'adr-0006-runtime-state-scope-lineage',
    title: {
      zh: 'ADR 0006: Durable Runtime-State Scope Lineage',
      en: 'ADR 0006: Durable Runtime-State Scope Lineage',
    },
    filePath: './content/echo-agent/adr/0006-runtime-state-scope-lineage.md',
  },
  {
    slug: 'adr-0007-atomic-journal-batch-commits',
    title: {
      zh: 'ADR 0007: Atomic Journal Batch Commits',
      en: 'ADR 0007: Atomic Journal Batch Commits',
    },
    filePath: './content/echo-agent/adr/0007-atomic-journal-batch-commits.md',
  },
  {
    slug: 'adr-0008-canonical-runtime-task-authority',
    title: {
      zh: 'ADR 0008: Canonical Runtime Task Authority',
      en: 'ADR 0008: Canonical Runtime Task Authority',
    },
    filePath: './content/echo-agent/adr/0008-canonical-runtime-task-authority.md',
  },
  {
    slug: 'adr-0009-tracked-input-receipts',
    title: {
      zh: 'ADR 0009: Tracked Active and Initial Input Receipts',
      en: 'ADR 0009: Tracked Active and Initial Input Receipts',
    },
    filePath: './content/echo-agent/adr/0009-tracked-input-receipts.md',
  },
  {
    slug: 'adr-0010-canonical-turn-receipt-accounting',
    title: {
      zh: 'ADR 0010: Canonical Turn Receipt Accounting',
      en: 'ADR 0010: Canonical Turn Receipt Accounting',
    },
    filePath: './content/echo-agent/adr/0010-canonical-turn-receipt-accounting.md',
  },
  {
    slug: 'adr-0011-typed-tool-output-artifact',
    title: {
      zh: 'ADR 0011: Typed Tool Output Artifact',
      en: 'ADR 0011: Typed Tool Output Artifact',
    },
    filePath: './content/echo-agent/adr/0011-typed-tool-output-artifact.md',
  },
  {
    slug: 'adr-0012-immutable-plugin-preparation',
    title: {
      zh: 'ADR 0012: Immutable plugin preparation generations',
      en: 'ADR 0012: Immutable plugin preparation generations',
    },
    filePath: './content/echo-agent/adr/0012-immutable-plugin-preparation.md',
  },
];
