// Generated by scripts/sync-docs.mjs. Do not edit by hand.

export const frameworkAdrDocs = [
  {
    slug: 'adr-0001-channel-session-sender-scope',
    title: {
      zh: 'ADR 0001: Sender-Scoped Channel Sessions',
      en: 'ADR 0001: Sender-Scoped Channel Sessions',
    },
    filePath: './content/echo-agent/adr/0001-channel-session-sender-scope.md',
  },
  {
    slug: 'adr-0002-sandbox-cancellation-cleanup',
    title: {
      zh: 'ADR 0002: Sandbox Cancellation Cleanup',
      en: 'ADR 0002: Sandbox Cancellation Cleanup',
    },
    filePath: './content/echo-agent/adr/0002-sandbox-cancellation-cleanup.md',
  },
  {
    slug: 'adr-0003-tracked-steer-lifecycle',
    title: {
      zh: 'ADR 0003: Tracked Steering Lifecycle',
      en: 'ADR 0003: Tracked Steering Lifecycle',
    },
    filePath: './content/echo-agent/adr/0003-tracked-steer-lifecycle.md',
  },
  {
    slug: 'adr-0004-async-file-store-ownership',
    title: {
      zh: 'ADR 0004: Async File Store Ownership',
      en: 'ADR 0004: Async File Store Ownership',
    },
    filePath: './content/echo-agent/adr/0004-async-file-store-ownership.md',
  },
  {
    slug: 'adr-0005-invocation-resource-lifetime',
    title: {
      zh: 'ADR 0005: Invocation Resource Lifetime Guards',
      en: 'ADR 0005: Invocation Resource Lifetime Guards',
    },
    filePath: './content/echo-agent/adr/0005-invocation-resource-lifetime.md',
  },
  {
    slug: 'adr-0006-runtime-state-scope-lineage',
    title: {
      zh: 'ADR 0006: Durable Runtime-State Scope Lineage',
      en: 'ADR 0006: Durable Runtime-State Scope Lineage',
    },
    filePath: './content/echo-agent/adr/0006-runtime-state-scope-lineage.md',
  },
  {
    slug: 'adr-0007-atomic-journal-batch-commits',
    title: {
      zh: 'ADR 0007: Atomic Journal Batch Commits',
      en: 'ADR 0007: Atomic Journal Batch Commits',
    },
    filePath: './content/echo-agent/adr/0007-atomic-journal-batch-commits.md',
  },
  {
    slug: 'adr-0008-canonical-runtime-task-authority',
    title: {
      zh: 'ADR 0008: Canonical Runtime Task Authority',
      en: 'ADR 0008: Canonical Runtime Task Authority',
    },
    filePath: './content/echo-agent/adr/0008-canonical-runtime-task-authority.md',
  },
  {
    slug: 'adr-0009-tracked-input-receipts',
    title: {
      zh: 'ADR 0009: Tracked Active and Initial Input Receipts',
      en: 'ADR 0009: Tracked Active and Initial Input Receipts',
    },
    filePath: './content/echo-agent/adr/0009-tracked-input-receipts.md',
  },
  {
    slug: 'adr-0010-canonical-turn-receipt-accounting',
    title: {
      zh: 'ADR 0010: Canonical Turn Receipt Accounting',
      en: 'ADR 0010: Canonical Turn Receipt Accounting',
    },
    filePath: './content/echo-agent/adr/0010-canonical-turn-receipt-accounting.md',
  },
  {
    slug: 'adr-0011-typed-tool-output-artifact',
    title: {
      zh: 'ADR 0011: Typed Tool Output Artifact',
      en: 'ADR 0011: Typed Tool Output Artifact',
    },
    filePath: './content/echo-agent/adr/0011-typed-tool-output-artifact.md',
  },
  {
    slug: 'adr-0012-immutable-plugin-preparation',
    title: {
      zh: 'ADR 0012: Immutable plugin preparation generations',
      en: 'ADR 0012: Immutable plugin preparation generations',
    },
    filePath: './content/echo-agent/adr/0012-immutable-plugin-preparation.md',
  },
  {
    slug: 'adr-0013-learning-examples-and-documentation-boundary',
    title: {
      zh: 'ADR 0013: Learning Examples and Documentation Boundary',
      en: 'ADR 0013: Learning Examples and Documentation Boundary',
    },
    filePath: './content/echo-agent/adr/0013-learning-examples-and-documentation-boundary.md',
  },
  {
    slug: 'adr-0014-framework-capability-placement',
    title: {
      zh: 'ADR 0014: Framework Capability Placement',
      en: 'ADR 0014: Framework Capability Placement',
    },
    filePath: './content/echo-agent/adr/0014-framework-capability-placement.md',
  },
  {
    slug: 'adr-0015-keyed-execution-admission',
    title: {
      zh: 'ADR 0015: Keyed Execution Admission',
      en: 'ADR 0015: Keyed Execution Admission',
    },
    filePath: './content/echo-agent/adr/0015-keyed-execution-admission.md',
  },
  {
    slug: 'adr-0016-delivery-ledger-contract',
    title: {
      zh: 'ADR 0016: Product-Neutral Delivery Ledger Contract',
      en: 'ADR 0016: Product-Neutral Delivery Ledger Contract',
    },
    filePath: './content/echo-agent/adr/0016-delivery-ledger-contract.md',
  },
  {
    slug: 'adr-0017-delivery-ledger-reconciliation',
    title: {
      zh: 'ADR 0017: Delivery Ledger Prepared Reconciliation',
      en: 'ADR 0017: Delivery Ledger Prepared Reconciliation',
    },
    filePath: './content/echo-agent/adr/0017-delivery-ledger-reconciliation.md',
  },
  {
    slug: 'adr-0018-agent-router-legacy-wire-boundary',
    title: {
      zh: 'ADR 0018: AgentRouter Legacy Wire Boundary',
      en: 'ADR 0018: AgentRouter Legacy Wire Boundary',
    },
    filePath: './content/echo-agent/adr/0018-agent-router-legacy-wire-boundary.md',
  },
  {
    slug: 'adr-0019-typed-delivery-ledger-api',
    title: {
      zh: 'ADR 0019: Typed Delivery Ledger API',
      en: 'ADR 0019: Typed Delivery Ledger API',
    },
    filePath: './content/echo-agent/adr/0019-typed-delivery-ledger-api.md',
  },
  {
    slug: 'adr-0020-structured-subagent-outcome-views',
    title: {
      zh: 'ADR 0020: Structured Subagent Outcome Views',
      en: 'ADR 0020: Structured Subagent Outcome Views',
    },
    filePath: './content/echo-agent/adr/0020-structured-subagent-outcome-views.md',
  },
  {
    slug: 'adr-0021-framework-native-domain-values',
    title: {
      zh: 'ADR 0021: Framework-Native Domain Values',
      en: 'ADR 0021: Framework-Native Domain Values',
    },
    filePath: './content/echo-agent/adr/0021-framework-native-domain-values.md',
  },
  {
    slug: 'adr-0022-typed-llm-timeouts',
    title: {
      zh: 'ADR 0022: Typed LLM Timeout Contract',
      en: 'ADR 0022: Typed LLM Timeout Contract',
    },
    filePath: './content/echo-agent/adr/0022-typed-llm-timeouts.md',
  },
  {
    slug: 'adr-0023-current-skill-frontmatter',
    title: {
      zh: 'ADR 0023: Current Skill Frontmatter Is the Only Skill Format',
      en: 'ADR 0023: Current Skill Frontmatter Is the Only Skill Format',
    },
    filePath: './content/echo-agent/adr/0023-current-skill-frontmatter.md',
  },
  {
    slug: 'adr-0024-unified-subagent-prompt-compilation',
    title: {
      zh: 'ADR 0024: Unified Subagent Prompt Compilation',
      en: 'ADR 0024: Unified Subagent Prompt Compilation',
    },
    filePath: './content/echo-agent/adr/0024-unified-subagent-prompt-compilation.md',
  },
  {
    slug: 'adr-0025-deterministic-command-cell-watcher',
    title: {
      zh: 'ADR 0025: Deterministic Command-Cell Watcher',
      en: 'ADR 0025: Deterministic Command-Cell Watcher',
    },
    filePath: './content/echo-agent/adr/0025-deterministic-command-cell-watcher.md',
  },
  {
    slug: 'adr-0026-official-skill-frontmatter-only',
    title: {
      zh: 'ADR 0026: SKILL.md Uses Official agentskills.io Fields Only',
      en: 'ADR 0026: SKILL.md Uses Official agentskills.io Fields Only',
    },
    filePath: './content/echo-agent/adr/0026-official-skill-frontmatter-only.md',
  },
  {
    slug: 'adr-0027-subagent-communication-primitives',
    title: {
      zh: 'ADR 0027: Subagent Communication Primitives (Uplink + Shared Control Plane)',
      en: 'ADR 0027: Subagent Communication Primitives (Uplink + Shared Control Plane)',
    },
    filePath: './content/echo-agent/adr/0027-subagent-communication-primitives.md',
  },
  {
    slug: 'adr-0029-shared-subagent-execution-admission',
    title: {
      zh: 'ADR 0029: Shared Subagent Execution Admission',
      en: 'ADR 0029: Shared Subagent Execution Admission',
    },
    filePath: './content/echo-agent/adr/0029-shared-subagent-execution-admission.md',
  },
  {
    slug: 'adr-0030-versioned-subagent-event-envelope',
    title: {
      zh: 'ADR 0030: Versioned Subagent Event Envelope',
      en: 'ADR 0030: Versioned Subagent Event Envelope',
    },
    filePath: './content/echo-agent/adr/0030-versioned-subagent-event-envelope.md',
  },
];
